# Setup
title:        Brain Life
tagline:      Life is a verb.
tagline2:      Enhancing neuroscientific workforce engagement in reproducible neuroimaging
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Franco Pestilli
  url:        http://www.francopestilli.com/

# Gems
gems:
  - jekyll-paginate

include:
  - _pages

#Others
markdown: kramdown
