# Setup
title:        brainlife
tagline:      Free cloud platform for secure neuroscience data analysis.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Franco Pestilli
  url:        http://www.francopestilli.com/

# Gems
gems:
  - jekyll-paginate

include:
  - _pages

#Others
markdown: kramdown
