# Setup
title:        brainlife
tagline:      Life is a verb.
tagline2:     Promoting neuroscience engagement in big-data, reproducible research.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Franco Pestilli
  url:        http://www.francopestilli.com/

# Gems
gems:
  - jekyll-paginate

include:
  - _pages

#Others
markdown: kramdown
