# Setup
title:        Brain Life
tagline:      Portal of services for a Brain's life
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Franco Pestilli
  url:        http://www.francopestilli.com/

# Gems
gems:
  - jekyll-paginate

include:
  - _pages

#Others
markdown: kramdown
